/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.obra.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.EscherFinal.obra.logic.dto.ObraDTO;
import co.edu.uniandes.csw.EscherFinal.obra.logic.dto.ObraPageDTO;
import co.edu.uniandes.csw.EscherFinal.obra.persistence.api._IObraPersistence;
import co.edu.uniandes.csw.EscherFinal.obra.persistence.converter.ObraConverter;
import co.edu.uniandes.csw.EscherFinal.obra.persistence.entity.ObraEntity;

public abstract class _ObraPersistence implements _IObraPersistence {

  	@PersistenceContext(unitName="EscherFinalPU")
 
	protected EntityManager entityManager;
	
	public ObraDTO createObra(ObraDTO obra) {
		ObraEntity entity=ObraConverter.persistenceDTO2Entity(obra);
		entityManager.persist(entity);
		return ObraConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ObraDTO> getObras() {
		Query q = entityManager.createQuery("select u from ObraEntity u");
		return ObraConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ObraPageDTO getObras(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ObraEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ObraEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ObraPageDTO response = new ObraPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ObraConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ObraDTO getObra(Long id) {
		return ObraConverter.entity2PersistenceDTO(entityManager.find(ObraEntity.class, id));
	}

	public void deleteObra(Long id) {
		ObraEntity entity=entityManager.find(ObraEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateObra(ObraDTO detail) {
		ObraEntity entity=entityManager.merge(ObraConverter.persistenceDTO2Entity(detail));
		ObraConverter.entity2PersistenceDTO(entity);
	}

}