/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.trabajo.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.EscherFinal.trabajo.logic.dto.TrabajoDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.persistence.entity.TrabajoEntity;

public abstract class _TrabajoConverter {

	public static TrabajoDTO entity2PersistenceDTO(TrabajoEntity entity){
		if (entity != null) {
			TrabajoDTO dto = new TrabajoDTO();
					dto.setResenha(entity.getResenha());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
			return dto;
		}else{
			return null;
		}
	}
	
	public static TrabajoEntity persistenceDTO2Entity(TrabajoDTO dto){
		if(dto!=null){
			TrabajoEntity entity=new TrabajoEntity();
					entity.setResenha(dto.getResenha());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<TrabajoDTO> entity2PersistenceDTOList(List<TrabajoEntity> entities){
		List<TrabajoDTO> dtos=new ArrayList<TrabajoDTO>();
		for(TrabajoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<TrabajoEntity> persistenceDTO2EntityList(List<TrabajoDTO> dtos){
		List<TrabajoEntity> entities=new ArrayList<TrabajoEntity>();
		for(TrabajoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}