/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.imagen.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.EscherFinal.imagen.logic.dto.ImagenDTO;
import co.edu.uniandes.csw.EscherFinal.imagen.persistence.entity.ImagenEntity;

public abstract class _ImagenConverter {

	public static ImagenDTO entity2PersistenceDTO(ImagenEntity entity){
		if (entity != null) {
			ImagenDTO dto = new ImagenDTO();
					dto.setName(entity.getName());
					dto.setId(entity.getId());
					dto.setUrl(entity.getUrl());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ImagenEntity persistenceDTO2Entity(ImagenDTO dto){
		if(dto!=null){
			ImagenEntity entity=new ImagenEntity();
					entity.setName(dto.getName());
			
					entity.setId(dto.getId());
			
					entity.setUrl(dto.getUrl());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ImagenDTO> entity2PersistenceDTOList(List<ImagenEntity> entities){
		List<ImagenDTO> dtos=new ArrayList<ImagenDTO>();
		for(ImagenEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ImagenEntity> persistenceDTO2EntityList(List<ImagenDTO> dtos){
		List<ImagenEntity> entities=new ArrayList<ImagenEntity>();
		for(ImagenDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}