/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.usuario.master.logic.dto;

import co.edu.uniandes.csw.EscherFinal.trabajo.logic.dto.TrabajoDTO;
import co.edu.uniandes.csw.EscherFinal.usuario.logic.dto.UsuarioDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _UsuarioMasterDTO {

 
    protected UsuarioDTO usuarioEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public UsuarioDTO getUsuarioEntity() {
        return usuarioEntity;
    }

    public void setUsuarioEntity(UsuarioDTO usuarioEntity) {
        this.usuarioEntity = usuarioEntity;
    }
    
    public List<TrabajoDTO> createtrabajo;
    public List<TrabajoDTO> updatetrabajo;
    public List<TrabajoDTO> deletetrabajo;
    public List<TrabajoDTO> listtrabajo;	
	
	
	
    public List<TrabajoDTO> getCreatetrabajo(){ return createtrabajo; };
    public void setCreatetrabajo(List<TrabajoDTO> createtrabajo){ this.createtrabajo=createtrabajo; };
    public List<TrabajoDTO> getUpdatetrabajo(){ return updatetrabajo; };
    public void setUpdatetrabajo(List<TrabajoDTO> updatetrabajo){ this.updatetrabajo=updatetrabajo; };
    public List<TrabajoDTO> getDeletetrabajo(){ return deletetrabajo; };
    public void setDeletetrabajo(List<TrabajoDTO> deletetrabajo){ this.deletetrabajo=deletetrabajo; };
    public List<TrabajoDTO> getListtrabajo(){ return listtrabajo; };
    public void setListtrabajo(List<TrabajoDTO> listtrabajo){ this.listtrabajo=listtrabajo; };	
	
	
}

