/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.autor.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.EscherFinal.autor.logic.dto.AutorDTO;
import co.edu.uniandes.csw.EscherFinal.autor.logic.dto.AutorPageDTO;
import co.edu.uniandes.csw.EscherFinal.autor.persistence.api._IAutorPersistence;
import co.edu.uniandes.csw.EscherFinal.autor.persistence.converter.AutorConverter;
import co.edu.uniandes.csw.EscherFinal.autor.persistence.entity.AutorEntity;

public abstract class _AutorPersistence implements _IAutorPersistence {

  	@PersistenceContext(unitName="EscherFinalPU")
 
	protected EntityManager entityManager;
	
	public AutorDTO createAutor(AutorDTO autor) {
		AutorEntity entity=AutorConverter.persistenceDTO2Entity(autor);
		entityManager.persist(entity);
		return AutorConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<AutorDTO> getAutors() {
		Query q = entityManager.createQuery("select u from AutorEntity u");
		return AutorConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public AutorPageDTO getAutors(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from AutorEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from AutorEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		AutorPageDTO response = new AutorPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(AutorConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public AutorDTO getAutor(Long id) {
		return AutorConverter.entity2PersistenceDTO(entityManager.find(AutorEntity.class, id));
	}

	public void deleteAutor(Long id) {
		AutorEntity entity=entityManager.find(AutorEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateAutor(AutorDTO detail) {
		AutorEntity entity=entityManager.merge(AutorConverter.persistenceDTO2Entity(detail));
		AutorConverter.entity2PersistenceDTO(entity);
	}

}