/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.video.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.EscherFinal.video.logic.dto.VideoDTO;
import co.edu.uniandes.csw.EscherFinal.video.logic.dto.VideoPageDTO;
import co.edu.uniandes.csw.EscherFinal.video.persistence.api._IVideoPersistence;
import co.edu.uniandes.csw.EscherFinal.video.persistence.converter.VideoConverter;
import co.edu.uniandes.csw.EscherFinal.video.persistence.entity.VideoEntity;

public abstract class _VideoPersistence implements _IVideoPersistence {

  	@PersistenceContext(unitName="EscherFinalPU")
 
	protected EntityManager entityManager;
	
	public VideoDTO createVideo(VideoDTO video) {
		VideoEntity entity=VideoConverter.persistenceDTO2Entity(video);
		entityManager.persist(entity);
		return VideoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<VideoDTO> getVideos() {
		Query q = entityManager.createQuery("select u from VideoEntity u");
		return VideoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public VideoPageDTO getVideos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from VideoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from VideoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		VideoPageDTO response = new VideoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(VideoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public VideoDTO getVideo(Long id) {
		return VideoConverter.entity2PersistenceDTO(entityManager.find(VideoEntity.class, id));
	}

	public void deleteVideo(Long id) {
		VideoEntity entity=entityManager.find(VideoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateVideo(VideoDTO detail) {
		VideoEntity entity=entityManager.merge(VideoConverter.persistenceDTO2Entity(detail));
		VideoConverter.entity2PersistenceDTO(entity);
	}

}