/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.trabajo.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.EscherFinal.trabajo.logic.dto.TrabajoDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.logic.dto.TrabajoPageDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.persistence.api._ITrabajoPersistence;
import co.edu.uniandes.csw.EscherFinal.trabajo.persistence.converter.TrabajoConverter;
import co.edu.uniandes.csw.EscherFinal.trabajo.persistence.entity.TrabajoEntity;

public abstract class _TrabajoPersistence implements _ITrabajoPersistence {

  	@PersistenceContext(unitName="EscherFinalPU")
 
	protected EntityManager entityManager;
	
	public TrabajoDTO createTrabajo(TrabajoDTO trabajo) {
		TrabajoEntity entity=TrabajoConverter.persistenceDTO2Entity(trabajo);
		entityManager.persist(entity);
		return TrabajoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<TrabajoDTO> getTrabajos() {
		Query q = entityManager.createQuery("select u from TrabajoEntity u");
		return TrabajoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public TrabajoPageDTO getTrabajos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from TrabajoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from TrabajoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		TrabajoPageDTO response = new TrabajoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(TrabajoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public TrabajoDTO getTrabajo(Long id) {
		return TrabajoConverter.entity2PersistenceDTO(entityManager.find(TrabajoEntity.class, id));
	}

	public void deleteTrabajo(Long id) {
		TrabajoEntity entity=entityManager.find(TrabajoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateTrabajo(TrabajoDTO detail) {
		TrabajoEntity entity=entityManager.merge(TrabajoConverter.persistenceDTO2Entity(detail));
		TrabajoConverter.entity2PersistenceDTO(entity);
	}

}