/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.usuario.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.EscherFinal.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.EscherFinal.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.EscherFinal.usuario.master.logic.api._IUsuarioMasterLogicService;
import co.edu.uniandes.csw.EscherFinal.usuario.master.logic.dto.UsuarioMasterDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.logic.api.ITrabajoLogicService;
import co.edu.uniandes.csw.EscherFinal.trabajo.logic.dto.TrabajoDTO;
import javax.inject.Inject;


public abstract class _UsuarioMasterMockLogicService implements _IUsuarioMasterLogicService {

    protected static ArrayList<UsuarioMasterDTO> usuarioMasterDtosList = new ArrayList<UsuarioMasterDTO>() ;
    @Inject
    protected ITrabajoLogicService trabajoPersistance;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;

    public UsuarioMasterDTO createMasterUsuario(UsuarioMasterDTO usuario) {

        usuarioPersistance.createUsuario(usuario.getUsuarioEntity());
        for (TrabajoDTO dto : usuario.getCreatetrabajo()) {
            trabajoPersistance.createTrabajo(dto);
        }
        usuarioMasterDtosList.add(usuario);
        return usuario;
    }

    public UsuarioMasterDTO getMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {
                return usuarioMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {

                for (TrabajoDTO dto : usuarioMasterDTO.getCreatetrabajo()) {
                    trabajoPersistance.deleteTrabajo(dto.getId());
                }
                usuarioPersistance.deleteUsuario(usuarioMasterDTO.getId());
                usuarioMasterDtosList.remove(usuarioMasterDTO);
            }
        }

    }

    public void updateMasterUsuario(UsuarioMasterDTO usuario) {

        // update Trabajo
        if (usuario.getUpdatetrabajo() != null) {
            for (TrabajoDTO dto : usuario.getUpdatetrabajo()) {
                trabajoPersistance.updateTrabajo(dto);
            }
        }
        // persist new Trabajo
        if (usuario.getCreatetrabajo() != null) {
            for (TrabajoDTO dto : usuario.getCreatetrabajo()) {
                TrabajoDTO persistedTrabajoDTO = trabajoPersistance.createTrabajo(dto);
                dto = persistedTrabajoDTO;
            }
        }
        // delete Trabajo
        if (usuario.getDeletetrabajo() != null) {
            for (TrabajoDTO dto : usuario.getDeletetrabajo()) {

                trabajoPersistance.deleteTrabajo(dto.getId());
            }
        }
    }
}