/* ========================================================================
 * Copyright 2014 EscherFinal
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 EscherFinal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.EscherFinal.trabajo.master.persistence.api;

import co.edu.uniandes.csw.EscherFinal.trabajo.master.persistence.entity.TrabajoobraEntity;
import co.edu.uniandes.csw.EscherFinal.obra.logic.dto.ObraDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.master.persistence.entity.TrabajoautorEntity;
import co.edu.uniandes.csw.EscherFinal.autor.logic.dto.AutorDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.master.persistence.entity.TrabajovideoEntity;
import co.edu.uniandes.csw.EscherFinal.video.logic.dto.VideoDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.master.persistence.entity.TrabajoimagenEntity;
import co.edu.uniandes.csw.EscherFinal.imagen.logic.dto.ImagenDTO;
import co.edu.uniandes.csw.EscherFinal.trabajo.master.logic.dto.TrabajoMasterDTO;
import java.util.List;

public interface _ITrabajoMasterPersistence {

	public TrabajoMasterDTO getTrabajo(Long trabajoId);
	
	
    public TrabajoobraEntity createTrabajoobraEntity(TrabajoobraEntity entity);
    public void deleteTrabajoobraEntity(Long trabajoId, Long obraId);
    public List<ObraDTO> getTrabajoobraEntityList(Long trabajoId);
    public TrabajoautorEntity createTrabajoautorEntity(TrabajoautorEntity entity);
    public void deleteTrabajoautorEntity(Long trabajoId, Long autorId);
    public List<AutorDTO> getTrabajoautorEntityList(Long trabajoId);
    public TrabajovideoEntity createTrabajovideoEntity(TrabajovideoEntity entity);
    public void deleteTrabajovideoEntity(Long trabajoId, Long videoId);
    public List<VideoDTO> getTrabajovideoEntityList(Long trabajoId);
    public TrabajoimagenEntity createTrabajoimagenEntity(TrabajoimagenEntity entity);
    public void deleteTrabajoimagenEntity(Long trabajoId, Long imagenId);
    public List<ImagenDTO> getTrabajoimagenEntityList(Long trabajoId);
   
  
}
